### ISSUE TITLE
Easier issue tracker discovery

### ISSUE THREAD

**Issue by rlipscombe** [opscode/supermarket#962]
When looking at an arbitrary cookbook, for example https://supermarket.chef.io/cookbooks/rabbitmq, it is really difficult to discover where to report issues with the cookbook.

This one is, if Google is to be believed, hosted at https://github.com/jjasghar/rabbitmq, but that's not obvious, because jjasghar is just one of half a dozen authors attached to the cookbook, and it appears to be owned by 'chef'.

It would be better if the "Details" panel for each cookbook had a link to github (or whatever) where issues could be reported.

**Comment by smith** [comment]
There is a "View Source" button on the side, but there was a previously existing bug that made this button disappear with new releases. It should be back now.
